[package]
name = "example-app"
version = "0.1.1"
edition = "2024"
publish = false
license = "AGPL-3.0-only"

[dependencies]
hector = { path = "../hector" }
tokio = { version = "1", features = ["full"] }
axum = "0.8"

[build-dependencies]
hector-build = { path = "../hector-build" }
